# -*- coding: utf-8 -*-
"""
Minecraft 一键开服器模块
支持原版服务端和 Fabric 服务端的下载、配置、启动
"""
import os
import json
import time
import threading
import subprocess
from pathlib import Path
import requests

try:
    from config import CONFIG
except ImportError:
    CONFIG = None

# 官方版本清单
VERSION_MANIFEST = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
# Fabric 服务端下载
FABRIC_META = "https://meta.fabricmc.net/v2/versions/loader"


def get_game_dir():
    """获取游戏根目录"""
    if CONFIG:
        return Path(CONFIG.get("game_dir", str(Path.home() / ".minecraft")))
    return Path.home() / ".minecraft"


def get_servers_dir():
    """获取服务器目录"""
    d = get_game_dir() / "voxel_servers"
    d.mkdir(parents=True, exist_ok=True)
    return d


def list_servers():
    """列出所有服务器"""
    d = get_servers_dir()
    servers = []
    if d.exists():
        for child in d.iterdir():
            if child.is_dir() and (child / "server.properties").exists():
                servers.append(child.name)
    return sorted(servers)


def get_server_info(name):
    """获取服务器信息"""
    d = get_servers_dir() / name
    props_file = d / "server.properties"
    info = {"name": name, "path": str(d), "port": "25565", "motd": "VoxelLauncher Server"}
    if props_file.exists():
        try:
            for line in props_file.read_text(encoding="utf-8").splitlines():
                if "=" in line:
                    k, v = line.split("=", 1)
                    if k.strip() == "server-port":
                        info["port"] = v.strip()
                    elif k.strip() == "motd":
                        info["motd"] = v.strip()
                    elif k.strip() == "max-players":
                        info["max_players"] = v.strip()
        except Exception:
            pass
    return info


def download_vanilla_server(version, progress_cb=None):
    """下载原版服务端"""
    # 获取版本信息
    resp = requests.get(VERSION_MANIFEST, timeout=30)
    manifest = resp.json()
    version_url = None
    for v in manifest.get("versions", []):
        if v.get("id") == version:
            version_url = v.get("url")
            break
    if not version_url:
        raise ValueError("找不到版本: " + version)

    resp = requests.get(version_url, timeout=30)
    version_info = resp.json()
    server_url = version_info.get("downloads", {}).get("server", {}).get("url")
    if not server_url:
        raise ValueError("该版本没有服务端")

    # 下载
    servers_dir = get_servers_dir()
    server_dir = servers_dir / ("vanilla-" + version)
    server_dir.mkdir(parents=True, exist_ok=True)
    jar_path = server_dir / "server.jar"

    if progress_cb:
        progress_cb("开始下载服务端...")

    resp = requests.get(server_url, stream=True, timeout=120)
    total = int(resp.headers.get("content-length", 0))
    downloaded = 0
    with open(jar_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
            downloaded += len(chunk)
            if progress_cb and total > 0:
                pct = downloaded * 100 // total
                progress_cb("下载中: {}%".format(pct))

    # 生成 eula.txt
    (server_dir / "eula.txt").write_text("eula=true\n", encoding="utf-8")

    # 生成 server.properties
    props = """#Minecraft server properties
#Generated by VoxelLauncher
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=VoxelLauncher Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=false
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
player-idle-timeout=0
rcon.password=
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
"""
    (server_dir / "server.properties").write_text(props, encoding="utf-8")

    if progress_cb:
        progress_cb("服务端下载完成!")

    return server_dir.name


def download_fabric_server(version, progress_cb=None, java_path="java"):
    """下载并安装 Fabric 服务端"""
    if progress_cb:
        progress_cb("获取 Fabric 版本信息...")

    # 获取最新的 fabric loader 版本
    resp = requests.get(FABRIC_META + "/" + version, timeout=30)
    loaders = resp.json()
    if not loaders:
        raise ValueError("找不到 Fabric 版本")
    loader_version = loaders[0].get("loader", {}).get("version")

    # 获取最新的 installer 版本
    installer_resp = requests.get("https://meta.fabricmc.net/v2/versions/installer", timeout=30)
    installers = installer_resp.json()
    installer_version = installers[0].get("version") if installers else "1.0.1"

    servers_dir = get_servers_dir()
    server_dir = servers_dir / ("fabric-" + version)
    server_dir.mkdir(parents=True, exist_ok=True)

    # 下载 Fabric 安装器
    installer_url = "https://maven.fabricmc.net/net/fabricmc/fabric-installer/{}/fabric-installer-{}.jar".format(
        installer_version, installer_version)
    installer_path = server_dir / "fabric-installer.jar"

    if progress_cb:
        progress_cb("下载 Fabric 安装器...")

    resp = requests.get(installer_url, stream=True, timeout=120)
    total = int(resp.headers.get("content-length", 0))
    downloaded = 0
    with open(installer_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
            downloaded += len(chunk)
            if progress_cb and total > 0:
                pct = downloaded * 100 // total
                progress_cb("下载中: {}%".format(pct))

    # 运行安装器安装服务端
    if progress_cb:
        progress_cb("安装 Fabric 服务端...")

    import subprocess
    cmd = [
        java_path, "-jar", str(installer_path),
        "server",
        "-mcversion", version,
        "-loader", loader_version,
        "-dir", str(server_dir)
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        raise RuntimeError("Fabric 安装失败: " + result.stderr[-500:])

    # Fabric 安装器会生成 fabric-server-launch.jar，保留原文件名
    launch_jar = server_dir / "fabric-server-launch.jar"
    if not launch_jar.exists():
        # 尝试找生成的 jar
        for f in server_dir.glob("*.jar"):
            if "fabric" in f.name.lower() and "launch" in f.name.lower():
                launch_jar = f
                break
    if not launch_jar.exists():
        raise RuntimeError("Fabric 安装后找不到启动 jar")

    # 下载 Minecraft 原版服务端 jar (Fabric 启动需要)
    if progress_cb:
        progress_cb("下载 Minecraft 服务端...")
    resp = requests.get(VERSION_MANIFEST, timeout=30)
    manifest = resp.json()
    version_url = None
    for v in manifest.get("versions", []):
        if v.get("id") == version:
            version_url = v.get("url")
            break
    if not version_url:
        raise ValueError("找不到版本: " + version)
    resp = requests.get(version_url, timeout=30)
    version_info = resp.json()
    server_url = version_info.get("downloads", {}).get("server", {}).get("url")
    if not server_url:
        raise ValueError("该版本没有服务端")
    vanilla_jar = server_dir / "server.jar"
    resp = requests.get(server_url, stream=True, timeout=120)
    total = int(resp.headers.get("content-length", 0))
    downloaded = 0
    with open(vanilla_jar, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
            downloaded += len(chunk)
            if progress_cb and total > 0:
                pct = downloaded * 100 // total
                progress_cb("下载服务端: {}%".format(pct))

    # 生成 eula.txt
    (server_dir / "eula.txt").write_text("eula=true\n", encoding="utf-8")

    # 生成 server.properties (同原版)
    props = """#Minecraft server properties
#Generated by VoxelLauncher
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=VoxelLauncher Fabric Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=false
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
player-idle-timeout=0
rcon.password=
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
"""
    (server_dir / "server.properties").write_text(props, encoding="utf-8")

    if progress_cb:
        progress_cb("Fabric 服务端下载完成!")

    return server_dir.name


class MinecraftServer:
    """Minecraft 服务器实例"""

    def __init__(self, name, java_path=None, memory="2G"):
        self.name = name
        self.server_dir = get_servers_dir() / name
        self.java_path = java_path or "java"
        self.memory = memory
        self.process = None
        self.output_callback = None
        self._running = False

    def start(self):
        """启动服务器"""
        if self._running:
            return False
        # 自动检测启动 jar: Fabric 用 fabric-server-launch.jar，原版用 server.jar
        jar_path = self.server_dir / "fabric-server-launch.jar"
        if not jar_path.exists():
            jar_path = self.server_dir / "server.jar"
        if not jar_path.exists():
            # 找任何可启动的 jar
            for f in self.server_dir.glob("*.jar"):
                if "launch" in f.name.lower() or "server" in f.name.lower():
                    jar_path = f
                    break
        if not jar_path.exists():
            raise FileNotFoundError("找不到服务器启动 jar")

        cmd = [
            self.java_path,
            "-Xmx" + self.memory,
            "-Xms" + self.memory,
            "-jar", str(jar_path),
            "nogui"
        ]

        self.process = subprocess.Popen(
            cmd,
            cwd=str(self.server_dir),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1
        )
        self._running = True

        # 启动输出读取线程
        t = threading.Thread(target=self._read_output, daemon=True)
        t.start()

        return True

    def _read_output(self):
        """读取服务器输出"""
        try:
            for line in self.process.stdout:
                line = line.strip()
                if line and self.output_callback:
                    self.output_callback(line)
        except Exception:
            pass
        finally:
            self._running = False
            if self.output_callback:
                self.output_callback("[服务器已停止]")

    def stop(self):
        """停止服务器"""
        if self.process and self._running:
            try:
                self.process.stdin.write("stop\n")
                self.process.stdin.flush()
                # 等待10秒
                try:
                    self.process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    self.process.kill()
            except Exception:
                try:
                    self.process.kill()
                except Exception:
                    pass
        self._running = False

    def send_command(self, cmd):
        """发送命令到服务器"""
        if self.process and self._running:
            try:
                self.process.stdin.write(cmd + "\n")
                self.process.stdin.flush()
                return True
            except Exception:
                return False
        return False

    def is_running(self):
        return self._running

    def get_local_ip(self):
        """获取本机局域网IP"""
        import socket
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(("8.8.8.8", 80))
            ip = s.getsockname()[0]
            s.close()
            return ip
        except Exception:
            return "127.0.0.1"

    def get_port(self):
        """获取服务器端口"""
        props_file = self.server_dir / "server.properties"
        if props_file.exists():
            try:
                for line in props_file.read_text(encoding="utf-8").splitlines():
                    if line.startswith("server-port="):
                        return line.split("=", 1)[1].strip()
            except Exception:
                pass
        return "25565"


def delete_server(name):
    """删除服务器"""
    import shutil
    d = get_servers_dir() / name
    if d.exists():
        shutil.rmtree(d)
        return True
    return False
